from pathlib import Path
from sqlmodel import SQLModel, Field
from pydantic import computed_field, HttpUrl
from pydantic_extra_types.currency_code import Currency
from enum import Enum
from urllib.parse import urljoin
from fastapi import UploadFile

from app.constants.product import IMAGE_ROUTE, ENDPOINT_PREFIX
from app.settings import get_settings


settings = get_settings()


class ProductTypes(Enum):
    """
    Enumeration of available product categories.

    Attributes
    ----------
    DRINK : str
        Beverage products (e.g., sodas, water, juices)
    SNACK : str
        Snack products (e.g., chips, candy, nuts)
    FOOD : str
        Food products (e.g., sandwiches, meals)
    """
    DRINK = "drink"
    SNACK = "snack"
    FOOD = "food"


class ProductBase(SQLModel):
    """
    Base model for product data shared across all product schemas.

    Attributes
    ----------
    name : str
        The product name (e.g., "Cola 0.33L")
    price : float
        Product price, must be non-negative (>= 0)
    type : ProductTypes
        Product category (DRINK, SNACK, or FOOD)
    currency : Currency, default="EUR"
        ISO 4217 currency code for the price
    """
    name: str
    price: float = Field(ge=0)
    type: ProductTypes
    currency: Currency = Field(default=Currency("EUR"))


class ProductCreate(ProductBase):
    """
    Schema for creating a new product via multipart/form-data upload.

    Extends ProductBase with an image file upload field. Used in API endpoints
    to accept product data and image simultaneously.

    Attributes
    ----------
    image : UploadFile
        The product image file to upload (will be converted to WebP format)

    Notes
    -----
    Inherits name, price, type, and currency from ProductBase.
    """
    image: UploadFile


class ProductPublic(ProductBase):
    """
    Public API schema for product responses.

    Extends ProductBase with an ID and dynamically computed image URL.
    Used when returning product data to clients.

    Attributes
    ----------
    id : int
        Unique product identifier
    image : HttpUrl
        Computed property that returns the full URL to fetch the product image

    Notes
    -----
    The image URL is constructed as: {host}{api_prefix}/products/{id}/image
    Inherits name, price, type, and currency from ProductBase.
    """
    id: int

    @computed_field
    @property
    def image(self) -> HttpUrl:
        """
        Construct the full HTTP URL for fetching the product image.

        Returns
        -------
        HttpUrl
            Complete URL to the product's image endpoint

        Examples
        --------
        >>> product = ProductPublic(id=1, name="Cola", price=2.5, type=ProductTypes.DRINK)
        >>> str(product.image)
        'http://localhost:8000/api/v1/products/1/image'
        """
        return HttpUrl(
            urljoin(
                str(settings.host),
                settings.api_prefix + ENDPOINT_PREFIX + f"/{self.id}" + IMAGE_ROUTE,
            )
        )


class Product(ProductBase, table=True):
    """
    Database model for storing products.

    SQLModel table representation with image storage via UUID-based filenames.
    The actual image files are stored as WebP format on disk.

    Attributes
    ----------
    id : int | None
        Primary key, auto-generated by database
    image_id : str
        UUID string used as the image filename (without extension)
    image_path : Path
        Computed property returning the full filesystem path to the image file

    Notes
    -----
    Images are stored as: {product_image_root_dir}/{image_id}.webp
    Inherits name, price, type, and currency from ProductBase.
    """
    id: int | None = Field(primary_key=True)
    image_id: str

    @property
    def image_path(self) -> Path:
        """
        Get the filesystem path to the product's image file.

        Returns
        -------
        Path
            Full path to the WebP image file on disk

        Examples
        --------
        >>> product = Product(id=1, image_id="abc123", ...)
        >>> product.image_path
        PosixPath('/data/product/images/abc123.webp')
        """
        return settings.product_image_root_dir / (self.image_id + ".webp")
